config/routes.rb
Rails.application.routes.draw do
  # Instead of localhost/users/sign_up -> it will be localhost/register
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  root to: 'pages#home'

  get 'about',         to: 'pages#about'
  get 'contact',       to: 'pages#contact'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  resources :portfolios, except: [:show]

end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: {draft: 0, published: 1}
  extend FriendlyId
  friendly_id :title, use: :slugged

  # Will not allow a blog post to be created unless a title and body is present
  validates_presence_of :title, :body

  # Blog belongs to topic
  # Added optional: true for section 10 lecture 113 because it would not 
  # let me created a new blog without adding a topic to it
  belongs_to :topic, optional: true
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  # access all: [:show, :index] -> Everyone is able to see the index and show
  # user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]} -> A regular user will not be able to do all this
  # site_admin: :all -> Admin has access to everything
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all
  # This tells the controller which layout out to choose
  # layout is the method and "blog" is the argument
  layout "blog"

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.page(params[:page]).per(5)
    @page_title = "My Portfolio Blog"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @page_title = @blog.title
    @seo_keywords = @blog.body
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
    redirect_to blogs_url, notice: 'Post status updated'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div class="blog-post">
  <h2 class="blog-post-title"><%= link_to blog.title.upcase, blog %></h2>
  <!-- distance_of_time_in_words(date,time) -->
  <!-- The method will display how much time since it has been created -->
  <p class="blog-post-meta">Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</p>

  <% if logged_in?(:site_admin) %>
  <p class="blog-post-meta">
    <%= link_to blog.status, toggle_status_blog_path(blog) %> /
    <%= link_to 'Edit', edit_blog_path(blog) %> /
    <%= link_to 'Delete', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
  <% end %>

  <p>
    <%= blog.body %>
  </p>
  
</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <% blog.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%# form.label :title %>
    <%= form.text_field :title, class: 'form-control', placeholder: 'Title' %>
  </div>

  <div class="form-group">
    <%# form.label :body %>
    <!-- The "rows: 15", is used for the height of the description box -->
    <%= form.text_area :body, class: 'form-control', rows: 15, placeholder: 'Content' %>
  </div>

  <div class="form-group">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

<!-- ############################################################# -->
<!-- 
  Using form_tag to build form:
  <%# form_tag(blogs_path) do %>
    <div class="form-group">
      <%# label_tag 'blog[title]' %>
      <%# text_field_tag 'blog[title]', nil, class: 'form-control' %>
      <%# text_field_tag 'blog[title]', blog.title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%# label_tag 'blog[body]' %>
      <%# text_area_tag 'blog[body]', blog.body, class: 'form-control', rows: 15 %>
    </div>
    <div class="form-group">
      <%# submit_tag 'Save', class: "btn btn-primary" %>
    </div>
  <%# end %>

  form_tags are better used for search engines not as much for CRUD apps
 -->

<!-- ############################################################# -->

app/views/blogs/edit.html.erb
<div class="col-sm-8 blog-main">
  <h1>Editing Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/index.html.erb
<div class="col-sm-8 blog-main">
  <%= paginate @blogs %><br>
  <!-- What the following is doing: -->
  <!-- Rails is looking for a partial called "blog" -->
  <!-- It will then pass in the instance variable @blogs -->
  <!-- Which in other words, passes the collection of blogs -->
  <!-- to the partial "blog" -->
  <%= render @blogs %>
  <%= paginate @blogs %>
</div>

app/views/blogs/new.html.erb
<div class="col-sm-8 blog-main">
  <h1>New Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<div class="col-sm-8 blog-main">
  
  <h2><%= @blog.title %></h2>

  <%= link_to 'Edit', edit_blog_path(@blog) if logged_in?(:site_admin) %>

  <p>
    <%= @blog.body %>
  </p>

</div>