config/routes.rb
Rails.application.routes.draw do
  # Instead of localhost/users/sign_up -> it will be localhost/register
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  root to: 'pages#home'

  get 'about',         to: 'pages#about'
  get 'contact',       to: 'pages#contact'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  resources :portfolios, except: [:show]

end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  validates_presence_of :title, :body

  # When Portfolio gets initialized, New Method, it will run the set_defaults method
  # Due to the carrierwave gem, the following is overwritten
  # after_initialize :set_defaults

  # Call Placeholder module from concerns folder
  # Due to the carrierwave gem, the following is overwritten
  # include Placeholder

  # PortfolioUploader is from the carrier gem for uploading images
  # mount_uploader tells portfolio to call carrierwave, the uploader is going
  # to apply to the :thumb_image and is going to use PortfolioUploader
  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  has_many :technologies

  # Do not accept if name is blank
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true, 
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  # When ruby_on_rails_portfolio_items is called, it will grab all the portfolio items
  # where the subtitle is "Ruby on Rails"
  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: "Ruby on Rails") }
  
  def self.angular
    where(subtitle: "Angular")
  end

  # Due to the carrierwave gem, the following is overwritten
  # def set_defaults
  #   self.main_image  ||= Placeholder.image_generator(height: "600", width: "400")
  #   self.thumb_image ||= Placeholder.image_generator(height: "350", width: "200")
  # end

end


# Explaination of ||=
# If the item is nil, it will run the code
# In other words, when creating a new portfolio, if no main image or thumb image is given,
# set_defaults will give it a default value
# Another way of looking at it is:
# if self.main_image == nil
#   self.main_image = "https://via.placeholder.com/600x400"
# end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all
  layout "portfolio"

  def index
    @portfolio_items = Portfolio.all
  end

  def show
  end

  def new
    @portfolio_item = Portfolio.new
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Portfolio item was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Record was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Record was removed.' }
    end
  end

  # Private methods are only available to this class only (Portfolios Controller)
  private

  def portfolio_params
    params.require(:portfolio).permit(:title, 
                                      :subtitle, 
                                      :body,
                                      :main_image,
                                      :thumb_image, 
                                      technologies_attributes: [:id, :name, :_destroy]
                                      )
  end

  def set_portfolio
    @portfolio_item = Portfolio.find(params[:id])
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "https://via.placeholder.com/#{height}x#{width}"
  end

  def portfolio_img img, type
    if img.model.main_image? || img.model.thumb_image?
      img
    elsif type == 'thumb' 
      image_generator(height: 350, width: 200)
    elsif type == 'main'
      image_generator(height: 600, width: 400)
    end
      
  end
end

#   self.main_image  ||= Placeholder.image_generator(height: "600", width: "400")
#   self.thumb_image ||= Placeholder.image_generator(height: "350", width: "200")

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |form| %>
  <% if @portfolio_item.errors.any? %>
    <% @portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :subtitle %>
        <%= form.text_field :subtitle, class: 'form-control' %>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a main image file <%= form.file_field :main_image, style: 'display:none;' %>
        </label>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a thumb image file <%= form.file_field :thumb_image, style: 'display:none;' %>
        </label>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: 'form-control', rows: 13 %>
      </div>
    </div>
  </div>

  <hr>

  <div class="col-md-12">
    <h2>Technologies Used:</h2>
    <div>
      <%= form.fields_for :technologies do |technology_form|%>
      <!-- 'f' is the local variable we passed in to the partial -->
        <%= render 'technology_fields', f: technology_form %>

        <div>
          <%= link_to_add_association 'Add Technology', f, :technologies %>
        </div>
      <% end %>
    </div>

    <div class="form-group">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="card">
  <%= image_tag portfolio_img(portfolio_item.thumb_image, 'thumb') %>
  <p class="card-text">
    <span><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></span> <%= portfolio_item.subtitle %>
  </p>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
  <h1>Edit this Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted">
  <div class="container">
    <div class="row sortable">
      <!-- The following is a MANUAL PARTIAL COLLECTION -->
      <!-- We manually declared it as a partial and passing in -->
      <!-- the exact name of the partial "portfolio_item" -->
      <!-- The "collection" is telling rails that we are passing  -->
      <!-- the instance variable @portfolio_items as the collection of data -->
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
  <h1>Create a new Portfolio Item</h1>

  <!-- We are sending @portfolio_item as a local data
  to the form partial -->
  <%= render 'form', portfolio_item: @portfolio_item %>  
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag portfolio_img(@portfolio_item.main_image, 'main'), width: '100%' %>      
    </div>

    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>

      <hr>

      <em><%= @portfolio_item.subtitle %></em>

      <p><%= @portfolio_item.body %></p>

      <hr>

      <h3>Technologies Used:</h3>

      <% @portfolio_item.technologies.each do |t| %>
        <p><%= t.name %></p>
      <% end %>

      <% if logged_in?(:site_admin) %>
      <div>
        <%= link_to "Edit Portfolio", edit_portfolio_path(@portfolio_item), class: "btn btn-warning" %>
      </div>
      <% end %>
    </div>
  </div>
</div>